-- MySQL Script generated by MySQL Workbench
-- Sat Oct  9 10:02:51 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Rarity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rarity` (
  `rarity` INT NOT NULL,
  `prop` DOUBLE NULL,
  PRIMARY KEY (`rarity`),
  UNIQUE INDEX `rarity_UNIQUE` (`rarity` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Type` (
  `type` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`type`),
  UNIQUE INDEX `id_UNIQUE` (`type` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kind`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kind` (
  `kind` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`kind`),
  UNIQUE INDEX `kind_UNIQUE` (`kind` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Item` (
  `id` INT NOT NULL,
  `rarity` INT NOT NULL,
  `type` INT NOT NULL,
  `kind` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `pic` VARCHAR(200) NULL,
  `cal` DOUBLE NULL,
  PRIMARY KEY (`id`, `rarity`, `type`, `kind`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Item_Rarity_idx` (`rarity` ASC) VISIBLE,
  INDEX `fk_Item_Type1_idx` (`type` ASC) VISIBLE,
  INDEX `fk_Item_kind1_idx` (`kind` ASC) VISIBLE,
  CONSTRAINT `fk_Item_Rarity`
    FOREIGN KEY (`rarity`)
    REFERENCES `mydb`.`Rarity` (`rarity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_Type1`
    FOREIGN KEY (`type`)
    REFERENCES `mydb`.`Type` (`type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_kind1`
    FOREIGN KEY (`kind`)
    REFERENCES `mydb`.`Kind` (`kind`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Supermarket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Supermarket` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `pickup` JSON NOT NULL,
  PRIMARY KEY (`id`, `pickup`),
  UNIQUE INDEX `idSupermarket_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `id` VARCHAR(64) NOT NULL,
  `name` VARCHAR(45) NULL,
  `lat` DOUBLE NULL,
  `lng` DOUBLE NULL,
  `score` INT NULL,
  `type` INT NULL,
  `kind` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_User_Type1_idx` (`type` ASC) VISIBLE,
  INDEX `fk_User_kind1_idx` (`kind` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_User_Type1`
    FOREIGN KEY (`type`)
    REFERENCES `mydb`.`Type` (`type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_kind1`
    FOREIGN KEY (`kind`)
    REFERENCES `mydb`.`Kind` (`kind`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
